[package]
name = "CyberKnight"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
custom_error = "1.9.2"
dotenv = "0.15.0"
env_logger = "0.10.0"
itertools = "0.11.0"
leptos = "0.4.3"
num = "0.4.1"
regex = "1.9.1"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.71"
tokio = { version = "1.29.1", features = ["full"] }
unicode-segmentation = "1.10.1"
