[package]
name = "cyber_knight_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
custom_error = "1.9.2"
env_logger = "0.10.0"
itertools = "0.11.0"
num = "0.4.1"
regex = "1.9.1"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.71"
unicode-segmentation = "1.10.1"

[profile.debug]
codegen-units = 1



[profile.release]
lto = true
codegen-units = 1