[package]
name = "CyberKnight"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
base64 = "0.21.2"
custom_error = "1.9.2"
derivative = "2.2.0"
env_logger = "0.10.0"
leptos = "0.4.3"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.71"
uuid = { version = "1.4.0", features = ["v4"] }
