services:
  CyberKnight:
    build:
      context: .
      dockerfile: Dockerfile
    image: cyber_knight_api
    container_name: cyber_knight_api
    ports:
      - "8081:8081"
    restart: unless-stopped

networks:
  default:
    driver: bridge
    name: cyber_knight
