[package]
name = "ciphers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
itertools = "0.11.0"
num = "0.4.1"
regex = "1.9.3"
unicode-segmentation = "1.10.1"
