[package]
name = "common"
version = "0.1.0"
edition = "2021"


[dependencies]
base64 = "0.21.2"
custom_error = "1.9.2"
encoding_rs = "0.8.32"
itertools = "0.11.0"
num = "0.4.1"
regex = "1.9.3"
serde = { version = "1.0.183", features = ["derive"] }
unicode-segmentation = "1.10.1"
